# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

spring:
  datasource:
    username: ${USER}
    password: ${PASSWORD}
    url: ${DATABASE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true