# example values

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: Плейбек.ру
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox


spring:
  datasource:
    username: ${USER}
    password: ${PASSWORD}
    url: ${DATABASE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect